# This file is generated by generator.rb. Do not edit this file.
#
# name: sample-library
#   description: This is a sample configuration file for the sample library.
#   version: 1.0.0

# sample-library (sample/sample1.rb)
class MyGeneratedClass
    def hello
        puts "hello"
    end
end


# sample-library (sample/sample2.rb)
class MyGeneratedClass
    def hello2
        hello
    end
end


