#!/usr/bin/env ruby
#
# generate libraries using libs.yaml
#
#  Copyright (C) 2015- Kyushu Institute of Technology.
#  Copyright (C) 2015- Shimane IT Open-Innovation Center.
#
#  This file is distributed under BSD 3-Clause License.
#
# (usage)
# ruby generator.rb mrubyc_folder [libs.yaml]
#

require 'yaml'

if !ARGV[0]
  puts <<EOL
(usage)
ruby generator.rb mrubyc_folder [libs.yaml]
EOL
  exit 1
end
mrubyc_folder = ARGV[0]

# read libs.yaml
libs_yaml = ARGV[1] || File.join(File.dirname(__FILE__), 'libs.yaml')
libs = YAML.load_file(libs_yaml)

if !libs['libs']
  puts "libs.yaml is invalid."
  exit 1
end

# generate mrblibs/extension.rb
extension_rb_header = "# This file is generated by generator.rb. Do not edit this file.\n#\n"
extension_rb = ""
libs['libs'].each do |lib|
    conf = YAML.load_file(File.join(File.dirname(__FILE__), lib, 'conf.yaml'))
    # generate header
    extension_rb_header += "# name: #{conf['name']}\n"
    extension_rb_header += "#   description: #{conf['description']}\n"
    extension_rb_header += "#   version: #{conf['version']}\n"
    # geneate extension.rb
    conf['ruby_files'].each do |ruby_file|
        extension_rb += "# #{conf['name']} (#{lib}/#{ruby_file})\n"
        extension_rb += File.read(File.join(File.dirname(__FILE__), lib, ruby_file)) + "\n"
    end
end
# output to mrblibs/extension.rb
if mrubyc_folder == '-'
    puts extension_rb_header, "\n", extension_rb
else
    File.open(File.join(mrubyc_folder, 'mrblib', 'extension.rb'), 'w') do |f|
        f.write(extension_rb_header)
        f.write("\n")
        f.write(extension_rb)
    end
end



