#!/usr/bin/env ruby
#
# generate libraries using libs.yaml
#
#  Copyright (C) 2015- Kyushu Institute of Technology.
#  Copyright (C) 2015- Shimane IT Open-Innovation Center.
#
#  This file is distributed under BSD 3-Clause License.
#
# (usage)
# ruby generator.rb mrubyc_folder [libs.yaml]
#

require 'yaml'

if !ARGV[0]
  puts <<EOL
(usage)
ruby generator.rb mrubyc_folder [libs.yaml]
EOL
  exit 1
end
mrubyc_folder = ARGV[0]

# Cache the script directory to avoid redundant File.dirname calls
libs_dir = File.dirname(__FILE__)

# read libs.yaml
libs_yaml = ARGV[1] || File.join(libs_dir, 'libs.yaml')
begin
  libs = YAML.load_file(libs_yaml)
rescue => e
  puts "Error reading libs.yaml: #{e.message}"
  exit 1
end

if !libs['libs']
  puts "libs.yaml is invalid."
  exit 1
end

# generate mrblibs/extension.rb
header_parts = ["# This file is generated by generator.rb. Do not edit this file.", "#"]
content_parts = []

libs['libs'].each do |lib|
    lib_dir_path = File.join(libs_dir, lib)
    conf_path = File.join(lib_dir_path, 'conf.yaml')

    begin
      conf = YAML.load_file(conf_path)
    rescue => e
      puts "Error reading #{conf_path}: #{e.message}"
      exit 1
    end

    # generate header
    header_parts << "# name: #{conf['name']}"
    header_parts << "#   description: #{conf['description']}"
    header_parts << "#   version: #{conf['version']}"

    # generate extension.rb content
    unless conf['ruby_files'].is_a?(Array)
      puts "Error: ruby_files in #{conf_path} must be an array"
      exit 1
    end

    conf['ruby_files'].each do |ruby_file|
        ruby_path = File.join(lib_dir_path, ruby_file)
        begin
          content_parts << "# #{conf['name']} (#{lib}/#{ruby_file})"
          content_parts << File.read(ruby_path)
          content_parts << ""
        rescue => e
          puts "Error reading #{ruby_path}: #{e.message}"
          exit 1
        end
    end
end

# Build complete output
extension_rb_header = header_parts.join("\n") + "\n"
extension_rb = content_parts.join("\n")

# output to mrblibs/extension.rb
if mrubyc_folder == '-'
    puts extension_rb_header, "\n", extension_rb
else
    output_path = File.join(mrubyc_folder, 'mrblib', 'extension.rb')
    output_dir = File.dirname(output_path)

    unless Dir.exist?(output_dir)
      puts "Error: Directory #{output_dir} does not exist"
      exit 1
    end

    begin
      File.write(output_path, extension_rb_header + "\n" + extension_rb)
    rescue => e
      puts "Error writing #{output_path}: #{e.message}"
      exit 1
    end
end



